/**
 * Auto-generated court map from https://entscheidsuche.ch/docs/Facetten_alle.json
 * Do not edit by hand. Regenerate with: npx tsx scripts/generate-court-map.ts
 */

export interface CourtInfo {
  name: string;
  canton?: string;
  level: 'federal' | 'cantonal';
}

export const COURT_MAP: Record<string, CourtInfo> = {
  'AG_AK': { name: 'Anwaltskommission', canton: 'AG', level: 'cantonal' as const },
  'AG_AUK': { name: 'Aufsichtskommission', canton: 'AG', level: 'cantonal' as const },
  'AG_BG': { name: 'Entscheidsammlung Baugesetzgebung', canton: 'AG', level: 'cantonal' as const },
  'AG_BV': { name: 'Verwaltungsbehörden', canton: 'AG', level: 'cantonal' as const },
  'AG_GB': { name: 'Entscheide Grundbuch und Notariat', canton: 'AG', level: 'cantonal' as const },
  'AG_JG': { name: 'Justizgericht', canton: 'AG', level: 'cantonal' as const },
  'AG_JL': { name: 'Justizleitung', canton: 'AG', level: 'cantonal' as const },
  'AG_OG': { name: 'Obergericht', canton: 'AG', level: 'cantonal' as const },
  'AG_RG': { name: 'Rekursgericht im Ausländerrecht', canton: 'AG', level: 'cantonal' as const },
  'AG_RR': { name: 'Regierungsrat', canton: 'AG', level: 'cantonal' as const },
  'AG_SK': { name: 'Schätzungskommission nach Baugesetz', canton: 'AG', level: 'cantonal' as const },
  'AG_SVWG': { name: 'Spezialverwaltungsgericht', canton: 'AG', level: 'cantonal' as const },
  'AG_UPL': { name: 'Upload', canton: 'AG', level: 'cantonal' as const },
  'AG_VB': { name: 'Verwaltungsbehörden', canton: 'AG', level: 'cantonal' as const },
  'AG_XX': { name: 'unbekanntes Gericht', canton: 'AG', level: 'cantonal' as const },
  'AI_BZG': { name: 'Bezirksgericht', canton: 'AI', level: 'cantonal' as const },
  'AI_KG': { name: 'Kantonsgericht', canton: 'AI', level: 'cantonal' as const },
  'AI_UPL': { name: 'Upload', canton: 'AI', level: 'cantonal' as const },
  'AI_XX': { name: 'Sammelwerk', canton: 'AI', level: 'cantonal' as const },
  'AR_KG': { name: 'Kantonsgericht', canton: 'AR', level: 'cantonal' as const },
  'AR_OG': { name: 'Obergericht', canton: 'AR', level: 'cantonal' as const },
  'AR_RR': { name: 'Regierungsrat', canton: 'AR', level: 'cantonal' as const },
  'AR_SRK': { name: 'Steuerrekurskommission', canton: 'AR', level: 'cantonal' as const },
  'AR_UPL': { name: 'Upload', canton: 'AR', level: 'cantonal' as const },
  'AR_VB': { name: 'Verwaltungsbehörden', canton: 'AR', level: 'cantonal' as const },
  'AR_XX': { name: 'unbekanntes Gericht', canton: 'AR', level: 'cantonal' as const },
  'BE_AK': { name: 'Kantonale Anwaltsaufsichtsbehörde', canton: 'BE', level: 'cantonal' as const },
  'BE_OG': { name: 'Obergericht', canton: 'BE', level: 'cantonal' as const },
  'BE_SRK': { name: 'Steuerrekurskommission', canton: 'BE', level: 'cantonal' as const },
  'BE_UPL': { name: 'Upload', canton: 'BE', level: 'cantonal' as const },
  'BE_VB': { name: 'Verwaltungsbehörden', canton: 'BE', level: 'cantonal' as const },
  'BE_VG': { name: 'Verwaltungsgericht', canton: 'BE', level: 'cantonal' as const },
  'BE_XX': { name: 'unbekanntes Gericht', canton: 'BE', level: 'cantonal' as const },
  'BL_EG': { name: 'Enteignungsgericht', canton: 'BL', level: 'cantonal' as const },
  'BL_KG': { name: 'Kantonsgericht', canton: 'BL', level: 'cantonal' as const },
  'BL_SG': { name: 'Steuergericht', canton: 'BL', level: 'cantonal' as const },
  'BL_UPL': { name: 'Upload', canton: 'BL', level: 'cantonal' as const },
  'BL_XX': { name: 'Sonstiges', canton: 'BL', level: 'cantonal' as const },
  'BL_ZMG': { name: 'Zwangsmassnahmengericht', canton: 'BL', level: 'cantonal' as const },
  'BS_APG': { name: 'Appellationsgericht', canton: 'BS', level: 'cantonal' as const },
  'BS_SVG': { name: 'Sozialversicherungsgericht', canton: 'BS', level: 'cantonal' as const },
  'BS_UPL': { name: 'Upload', canton: 'BS', level: 'cantonal' as const },
  'BS_XX': { name: 'unbekanntes Gericht', canton: 'BS', level: 'cantonal' as const },
  'CH_BGB': { name: 'Bundesgericht (BGE via Uni Bern)', level: 'federal' as const },
  'CH_BGE': { name: 'Bundesgericht (BGE)', level: 'federal' as const },
  'CH_BGer': { name: 'Bundesgericht', level: 'federal' as const },
  'CH_BR': { name: 'Bundesrat', level: 'federal' as const },
  'CH_BSTG': { name: 'Bundesstrafgericht', level: 'federal' as const },
  'CH_BVGE': { name: 'Bundesverwaltungsgericht', level: 'federal' as const },
  'CH_EDÖB': { name: 'Eidgenössischer Datenschutz- und Öffentlichkeitsbeauftragter (EDÖB)', level: 'federal' as const },
  'CH_PATG': { name: 'Bundespatentgericht', level: 'federal' as const },
  'CH_UPL': { name: 'Upload', level: 'federal' as const },
  'CH_VB': { name: 'Verwaltungspraxis der Bundesbehörden (1987-2017)', level: 'federal' as const },
  'CH_WBK': { name: 'Wettbewerbskommission', level: 'federal' as const },
  'CH_XX': { name: 'unbekanntes Gericht', level: 'federal' as const },
  'FR_TAMA': { name: 'Schiedsgericht in Sachen Kranken- und Unfallversicherung', canton: 'FR', level: 'cantonal' as const },
  'FR_TC': { name: 'Kantonsgericht', canton: 'FR', level: 'cantonal' as const },
  'FR_UPL': { name: 'Upload', canton: 'FR', level: 'cantonal' as const },
  'FR_XX': { name: 'unbekanntes Gericht', canton: 'FR', level: 'cantonal' as const },
  'GE_CAPJ': { name: 'Court d\'appel du pouvoir judiciaire', canton: 'GE', level: 'cantonal' as const },
  'GE_CJ': { name: 'Cour de Justice (Cour civile)', canton: 'GE', level: 'cantonal' as const },
  'GE_TAPI': { name: 'Tribunal administratif de première instance en matière fiscale', canton: 'GE', level: 'cantonal' as const },
  'GE_TP': { name: 'Tribunal pénal', canton: 'GE', level: 'cantonal' as const },
  'GE_UPL': { name: 'Upload', canton: 'GE', level: 'cantonal' as const },
  'GE_XX': { name: 'unbekanntes Gericht', canton: 'GE', level: 'cantonal' as const },
  'GL_KG': { name: 'Kantonsgericht', canton: 'GL', level: 'cantonal' as const },
  'GL_OG': { name: 'Obergericht', canton: 'GL', level: 'cantonal' as const },
  'GL_UPL': { name: 'Upload', canton: 'GL', level: 'cantonal' as const },
  'GL_VG': { name: 'Verwaltungsgericht', canton: 'GL', level: 'cantonal' as const },
  'GL_XX': { name: 'sonstige Gerichte', canton: 'GL', level: 'cantonal' as const },
  'GR_KG': { name: 'Kantonsgericht', canton: 'GR', level: 'cantonal' as const },
  'GR_UPL': { name: 'Upload', canton: 'GR', level: 'cantonal' as const },
  'GR_VG': { name: 'Verwaltungsgericht', canton: 'GR', level: 'cantonal' as const },
  'GR_XX': { name: 'unbekanntes Gericht', canton: 'GR', level: 'cantonal' as const },
  'JU_TC': { name: 'Tribunal Cantonal', canton: 'JU', level: 'cantonal' as const },
  'JU_TPI': { name: 'Tribunal de première instance', canton: 'JU', level: 'cantonal' as const },
  'JU_UPL': { name: 'Upload', canton: 'JU', level: 'cantonal' as const },
  'JU_XX': { name: 'unbekanntes Gericht', canton: 'JU', level: 'cantonal' as const },
  'LU_AUK': { name: 'Aufsichtsbehörden und Kommissionen', canton: 'LU', level: 'cantonal' as const },
  'LU_AVW': { name: 'andere Verwaltungsbehörden', canton: 'LU', level: 'cantonal' as const },
  'LU_BKD': { name: 'Bildungs- und Kulturdepartement', canton: 'LU', level: 'cantonal' as const },
  'LU_BZG': { name: 'Erstinstanzliche Gerichte', canton: 'LU', level: 'cantonal' as const },
  'LU_GSD': { name: 'Gesundheits- und Sozialdepartement', canton: 'LU', level: 'cantonal' as const },
  'LU_JSD': { name: 'Justiz- und Sicherheitsdepartement', canton: 'LU', level: 'cantonal' as const },
  'LU_KG': { name: 'Kantonsgericht', canton: 'LU', level: 'cantonal' as const },
  'LU_OG': { name: 'Obergericht', canton: 'LU', level: 'cantonal' as const },
  'LU_RR': { name: 'Regierungsrat', canton: 'LU', level: 'cantonal' as const },
  'LU_RSH': { name: 'Regierungsstatthalter', canton: 'LU', level: 'cantonal' as const },
  'LU_SA': { name: 'Kantonsgericht', canton: 'LU', level: 'cantonal' as const },
  'LU_UPL': { name: 'Upload', canton: 'LU', level: 'cantonal' as const },
  'LU_VWG': { name: 'Verwaltungsgericht', canton: 'LU', level: 'cantonal' as const },
  'LU_XX': { name: 'unbekanntes Gericht', canton: 'LU', level: 'cantonal' as const },
  'NE_ARA': { name: 'Autorité de recours des avocates, des avocats et du notariat', canton: 'NE', level: 'cantonal' as const },
  'NE_ASL': { name: 'Autorité de surveillance LP', canton: 'NE', level: 'cantonal' as const },
  'NE_ASS': { name: 'Autorité supérieure de surveillance LP', canton: 'NE', level: 'cantonal' as const },
  'NE_ATS': { name: 'Autorité tutélaire de surveillance', canton: 'NE', level: 'cantonal' as const },
  'NE_CA': { name: 'Autorité de surveillance des avocats', canton: 'NE', level: 'cantonal' as const },
  'NE_CN': { name: 'Autorité de surveillance du notariat', canton: 'NE', level: 'cantonal' as const },
  'NE_TC': { name: 'Tribunal Cantonal', canton: 'NE', level: 'cantonal' as const },
  'NE_TR': { name: 'Tribunaux régional - Civil', canton: 'NE', level: 'cantonal' as const },
  'NE_UPL': { name: 'Upload', canton: 'NE', level: 'cantonal' as const },
  'NE_XX': { name: 'unbekanntes Gericht', canton: 'NE', level: 'cantonal' as const },
  'NW_OG': { name: 'Gerichte', canton: 'NW', level: 'cantonal' as const },
  'NW_UPL': { name: 'Upload', canton: 'NW', level: 'cantonal' as const },
  'NW_XX': { name: 'unbekanntes Gericht', canton: 'NW', level: 'cantonal' as const },
  'OW_OG': { name: 'Amtsbericht über die Rechtspflege (AbR)', canton: 'OW', level: 'cantonal' as const },
  'OW_UPL': { name: 'Upload', canton: 'OW', level: 'cantonal' as const },
  'OW_VB': { name: 'Gerichts- und Verwaltungsentscheide (OGVE)', canton: 'OW', level: 'cantonal' as const },
  'OW_VG': { name: 'Verwaltungs- und Verwaltungsgerichtsentscheide (VVGE)', canton: 'OW', level: 'cantonal' as const },
  'OW_XX': { name: 'Sonstiges', canton: 'OW', level: 'cantonal' as const },
  'SG_ABSK': { name: 'Kantonale Aufsichtsbehörde für Schuldbetreibung und Konkurs', canton: 'SG', level: 'cantonal' as const },
  'SG_DEP': { name: 'Verwaltungsbehörden', canton: 'SG', level: 'cantonal' as const },
  'SG_HG': { name: 'Handelsgericht', canton: 'SG', level: 'cantonal' as const },
  'SG_KG': { name: 'Kantonsgericht', canton: 'SG', level: 'cantonal' as const },
  'SG_UPL': { name: 'Upload', canton: 'SG', level: 'cantonal' as const },
  'SG_VG': { name: 'Verwaltungsgericht', canton: 'SG', level: 'cantonal' as const },
  'SG_VSG': { name: 'Versicherungsgericht', canton: 'SG', level: 'cantonal' as const },
  'SG_VWEK': { name: 'Verwaltungsrekurskommission', canton: 'SG', level: 'cantonal' as const },
  'SG_XX': { name: 'unbekanntes Gericht', canton: 'SG', level: 'cantonal' as const },
  'SH_OG': { name: 'Obergericht', canton: 'SH', level: 'cantonal' as const },
  'SH_UPL': { name: 'Upload', canton: 'SH', level: 'cantonal' as const },
  'SH_XX': { name: 'unbekanntes Gericht', canton: 'SH', level: 'cantonal' as const },
  'SO_OG': { name: 'Obergericht', canton: 'SO', level: 'cantonal' as const },
  'SO_SK': { name: 'Schätzungskommission', canton: 'SO', level: 'cantonal' as const },
  'SO_STG': { name: 'Steuergericht', canton: 'SO', level: 'cantonal' as const },
  'SO_UPL': { name: 'Upload', canton: 'SO', level: 'cantonal' as const },
  'SO_VG': { name: 'Verwaltungsgericht', canton: 'SO', level: 'cantonal' as const },
  'SO_VSG': { name: 'Versicherungsgericht', canton: 'SO', level: 'cantonal' as const },
  'SO_XX': { name: 'unbekanntes Gericht', canton: 'SO', level: 'cantonal' as const },
  'SZ_KG': { name: 'Kantonsgericht', canton: 'SZ', level: 'cantonal' as const },
  'SZ_UPL': { name: 'Upload', canton: 'SZ', level: 'cantonal' as const },
  'SZ_VG': { name: 'Verwaltungsgericht', canton: 'SZ', level: 'cantonal' as const },
  'SZ_XX': { name: 'unbekanntes Gericht', canton: 'SZ', level: 'cantonal' as const },
  'TA_DZK': { name: 'Disziplinarkammer des Schweizer Sports', canton: 'TA', level: 'cantonal' as const },
  'TA_SST': { name: 'Schweizer Sportgericht', canton: 'TA', level: 'cantonal' as const },
  'TA_XX': { name: 'unbekanntes Gericht', canton: 'TA', level: 'cantonal' as const },
  'TG_OG': { name: 'Obergericht', canton: 'TG', level: 'cantonal' as const },
  'TG_UPL': { name: 'Upload', canton: 'TG', level: 'cantonal' as const },
  'TG_XX': { name: 'unbekanntes Gericht', canton: 'TG', level: 'cantonal' as const },
  'TI_CARP': { name: 'Corte di appello e di revisione penale', canton: 'TI', level: 'cantonal' as const },
  'TI_CATI': { name: 'Camera di diritto tributario', canton: 'TI', level: 'cantonal' as const },
  'TI_CRP': { name: 'Camera dei ricorsi penali', canton: 'TI', level: 'cantonal' as const },
  'TI_GIAR': { name: 'Il Giudice dell\'istruzione e dell\'arresto', canton: 'TI', level: 'cantonal' as const },
  'TI_GPC': { name: 'Ufficio del giudice dei provvedimenti coercitivi', canton: 'TI', level: 'cantonal' as const },
  'TI_PP': { name: 'Il Presidente della Pretura Penale', canton: 'TI', level: 'cantonal' as const },
  'TI_TCA': { name: 'Tribunale cantonale amministrativo', canton: 'TI', level: 'cantonal' as const },
  'TI_TCAS': { name: 'Tribunale cantonale delle assicurazioni', canton: 'TI', level: 'cantonal' as const },
  'TI_TE': { name: 'Tribunale di espropriazione', canton: 'TI', level: 'cantonal' as const },
  'TI_TPC': { name: 'Tribunale penale cantonale', canton: 'TI', level: 'cantonal' as const },
  'TI_TRAC': { name: 'Tribunale di appello diritto civile', canton: 'TI', level: 'cantonal' as const },
  'TI_TRAP': { name: 'Tribunale di appello diritto penale', canton: 'TI', level: 'cantonal' as const },
  'TI_TRPI': { name: 'Tribunale della pianificazione', canton: 'TI', level: 'cantonal' as const },
  'TI_UPL': { name: 'Upload', canton: 'TI', level: 'cantonal' as const },
  'TI_XX': { name: 'Diversi', canton: 'TI', level: 'cantonal' as const },
  'UR_OG': { name: 'Obergericht', canton: 'UR', level: 'cantonal' as const },
  'UR_UPL': { name: 'Upload', canton: 'UR', level: 'cantonal' as const },
  'UR_XX': { name: 'unbekanntes Gericht', canton: 'UR', level: 'cantonal' as const },
  'VD_SR': { name: 'Conseil d\'État', canton: 'VD', level: 'cantonal' as const },
  'VD_TC': { name: 'Tribunal cantonal', canton: 'VD', level: 'cantonal' as const },
  'VD_TN': { name: 'Tribunal neutre', canton: 'VD', level: 'cantonal' as const },
  'VD_TPHA': { name: 'Tribunal de Prud\'hommes de l\'Administration cantonale', canton: 'VD', level: 'cantonal' as const },
  'VD_UPL': { name: 'Upload', canton: 'VD', level: 'cantonal' as const },
  'VD_XX': { name: 'unbekanntes Gericht', canton: 'VD', level: 'cantonal' as const },
  'VS_AG': { name: 'Arbeitsgericht', canton: 'VS', level: 'cantonal' as const },
  'VS_BZG': { name: 'Bezirksgericht', canton: 'VS', level: 'cantonal' as const },
  'VS_SRK': { name: 'Kantonale Steuerrekurskommission', canton: 'VS', level: 'cantonal' as const },
  'VS_TC': { name: 'Kantonsgericht', canton: 'VS', level: 'cantonal' as const },
  'VS_UPL': { name: 'Upload', canton: 'VS', level: 'cantonal' as const },
  'VS_XX': { name: 'Sonstiges', canton: 'VS', level: 'cantonal' as const },
  'ZG_OG': { name: 'Obergericht', canton: 'ZG', level: 'cantonal' as const },
  'ZG_UPL': { name: 'Upload', canton: 'ZG', level: 'cantonal' as const },
  'ZG_VG': { name: 'Verwaltungsgericht', canton: 'ZG', level: 'cantonal' as const },
  'ZG_XX': { name: 'unbekanntes Gericht', canton: 'ZG', level: 'cantonal' as const },
  'ZH_BK': { name: 'Bezirksgerichte', canton: 'ZH', level: 'cantonal' as const },
  'ZH_BRK': { name: 'Baurekursgericht', canton: 'ZH', level: 'cantonal' as const },
  'ZH_HG': { name: 'Handelsgericht', canton: 'ZH', level: 'cantonal' as const },
  'ZH_KSG': { name: 'Kassationsgericht', canton: 'ZH', level: 'cantonal' as const },
  'ZH_OG': { name: 'Obergericht', canton: 'ZH', level: 'cantonal' as const },
  'ZH_SOBE': { name: 'Andere Behörden und Gerichte', canton: 'ZH', level: 'cantonal' as const },
  'ZH_SRK': { name: 'Steuerrekursgericht', canton: 'ZH', level: 'cantonal' as const },
  'ZH_SVG': { name: 'Sozialversicherungsgericht', canton: 'ZH', level: 'cantonal' as const },
  'ZH_UPL': { name: 'Upload', canton: 'ZH', level: 'cantonal' as const },
  'ZH_VG': { name: 'Verwaltungsgericht', canton: 'ZH', level: 'cantonal' as const },
  'ZH_XX': { name: 'unbekanntes Gericht', canton: 'ZH', level: 'cantonal' as const },
};
