/**
 * Post-build: read built single-file HTML widgets and write them
 * as TypeScript string constants for embedding in the server bundle.
 *
 * Writes to both widgets-common/dist/ and mcp-servers-http/src/lib/
 * so the HTTP server can import them directly.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const widgets = [
  { name: 'jurisprudenceBrowser', file: 'jurisprudence-browser/index.html' },
  { name: 'adversarialDashboard', file: 'adversarial-dashboard/index.html' },
];

let output = '// Auto-generated by embed-html.mjs — do not edit manually.\n\n';

for (const w of widgets) {
  const html = readFileSync(resolve(root, 'dist', w.file), 'utf-8');
  const escaped = JSON.stringify(html);
  output += `export const ${w.name}Html = ${escaped};\n\n`;
}

// Write to widgets-common dist
const outDir = resolve(root, 'dist');
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'embedded-widgets.ts'), output);

// Write to mcp-servers-http/src/lib for direct import by server code
const httpLibDir = resolve(root, '../../mcp-servers-http/src/lib');
mkdirSync(httpLibDir, { recursive: true });
writeFileSync(resolve(httpLibDir, 'embedded-widgets.ts'), output);

console.log('Embedded widget HTML strings written to dist/ and mcp-servers-http/src/lib/');
